export { ClockWidget } from './ClockWidget';
export { TimerWidget } from './TimerWidget';
export { default as ActivityWidget } from './ActivityWidget';
export { ImageWidget } from './ImageWidget';
export { VideoWidget } from './VideoWidget';
export { NotesWidget } from './NotesWidget';
export { QuickLinksWidget } from './QuickLinksWidget';
export { default as NetworkMonitorWidget } from './NetworkMonitorWidget';
export { default as TemperatureWidget } from './TemperatureWidget';
export { default as RamUsageWidget } from './RamUsageWidget';
export { default as DiskUsageWidget } from './DiskUsageWidget';
export { default as PDFWidget } from './PDFWidget';
